### ISSUE TITLE
easy-install.sh doesn't quite work out of the box

### ISSUE THREAD

**Issue by chambbj** [Applied-GeoSolutions/lidar2dems#13]
@matthewhanson You don't currently host your easy-install.sh as part of this repo, but I thought I'd provide some feedback attempting to run it on a clean trusty64 box on vagrant. I noticed that your easy-install didn't quite work for me. Here are a few notes that I compiled while working through it all.

1) I had to install setuptools on my own (required by gippy and lidar2dems).
2) Many of your downloaded source code ends up being nested (e.g., points2grid is located within LASzip). I guess this isn't necessarily a problem, but I don't think it's what you intended. It took me a minute to figure out where all the downloaded code had gone.
3) I had to install swig on my own via apt-get (required by at least gippy).
4) Had trouble finding cpl_port.h while installing lidar2dems. Installing python-gdal via apt-get fixed this.
5) Needed to install libxslt1-dev via apt-get.

**Comment by matthewhanson** [comment]
Thanks a lot brad. This is a great help. I thought I had worked out all the dependencies, but will update the script this weekend,  Thanks again,
