### ISSUE TITLE
l2d_chm large sites segfault

### ISSUE THREAD

**Issue by F-Sullivan** [Applied-GeoSolutions/lidar2dems#16]
For particularly large footprint sites (for example, site 212 50697x21767 pixels), calling l2d_chm with VRT inputs throws a segmentation fault. I used gdal_translate to generate tif files for the DTM and DSM of the site and was able to use these successfully as the input for l2d_chm. I repeated this workaround on three other sites.

**Comment by matthewhanson** [comment]
This should be handled by subtracting the two on a feature by feature basis.

Also, if something other than GIPPY is used to do the subtraction, GIPPY might be able to be removed as a dependency.

**Comment by matthewhanson** [comment]
fixed in v1.1.0 by creating CHM for each feature in site shapefile (if one provided).  If not, it will create a single CHM using the final DTM/DSM images (VRT usually).
