### ISSUE TITLE
Installation at for B. Wedeaux et al.

### ISSUE THREAD

**Issue by stephenhagen** [Applied-GeoSolutions/lidar2dems#17]
A group at Cambridge in England is using the software and they have run into an issue that they describe in this email:

############
Dear Steve,

My colleague Michele Dalponte has been helping out with analysing my 2011 lidar with las2dems. However, we have been so far unsuccesful, as the program is not creating any output files. We were hoping you might be able to make a few suggestions as to where the error could lie. The area is very large with more than 1000 las tiles of 1km2, but I have splitted the site polygon into smaller units. The same problem persists when not using the shapefile and also when analysing single files. He sent me the following report:

This is the command I use:

l2d_classify /media/michele/BEA_HD_1/raw_las_files/AOI/ -s /media/michele/BEA_HD_1/KFCP_cover_classes_split.shp --outdir /media/michele/BEA_HD_1/raw_las_files_class/

And this the message I get (one for each file in AOI)

Classifying 0 files into KFCP_cover_classes_split-0_l2d_s1c2.las
Created temp merged las file d0f7e505-53c4-4cad-b889-b6ace18e0504.las in 0:00:00.042752
PDAL: file not found: /media/michele/BEA_HD_1/raw_las_files_class/d0f7e505-53c4-4cad-b889-b6ace18e0504.las

Completed KFCP_cover_classes_split-0_l2d_s1c2.las in 0:00:00.390270
Classifying 0 files into KFCP_cover_classes_split-1_l2d_s1c2.las
Created temp merged las file 920dc903-d03a-4d4f-91d5-1a8cc49d9d29.las in 0:00:00.040098

Thanks for your help,

Beatrice
Béatrice Wedeux

PhD student
Forest Ecology and Conservation Group
University of Cambridge
################

**Comment by matthewhanson** [comment]
The key message here is this:
********************
Classifying 0 files into KFCP_cover_classes_split-0_l2d_s1c2.las
********************

It appears that no las files are found.  (note that it should not attempt to proceed past this point, filed issue #18)

Confirm that there are las files in the /media/michele/BEA_HD_1/raw_las_files/AOI/ directory, and that they have a .las extension.

**Comment by stephenhagen** [comment]
Here is her follow up email (she should just post):
Hi Steve,

Yes, the files in that directory are las files and have a .las extension, their Properties are "FugroViewer Lidar File (.las)" (because the files are set to be visualised using FugroViewer)

I could have mentioned that Michele has been logging in to his work station remotely and has been using Linux through a Virtual Machine on a Windows computer - in case that affects the detection of files on external hard drives.

Best,
Beatrice

**Comment by matthewhanson** [comment]
If they are las files, then that means it's not finding any of them that are within the shapefile bounds.   Verify that the shapefile is in the same projection as the las files.

If completely stuck, feel free to send me the shapefile and a las file that falls within it's geometry.

**Comment by stephenhagen** [comment]
She uploaded a shapefile and a single tile. I put them on /mimas/projects/cmsindo/cambridge/.

The weird thing is that, on rio I can call:
l2d_classify . -s KFCP_cover_classes_split.shp --outdir LASclass

and it works. So, something is up with her installation. I'll test it on our test server...

**Comment by stephenhagen** [comment]
I copied the same files to our test server which should mimic a fresh install. I can't reproduce the problem. All seems to be working fine over here. Should I ask them to reinstall? (I'll also ask them to join github...)

**Comment by beawedeux** [comment]
Dear Matthew and Steve,
Thanks for your help so far. We will attempt to reinstall and let you know if teh second attempt is more successful.
Best wishes,
Beatrice

**Comment by matthewhanson** [comment]
unable to reproduce
